### ISSUE TITLE
Tutorial on getting Discord API Key.

### ISSUE THREAD

**Issue by ryanlong1004** [ryanlong1004/blitzcrank_discord_bot_v2#2]
Put together a tutorial on creating a Discord API key.

**Comment by MarlonJMejia** [comment]
https://github.com/ryanlong1004/blitzcrank_discord_bot_v2/pull/5 - has a tutorial on how to create a basic token and associate a server made by the user to test the bot.

Any feedback is welcome.

**Comment by ryanlong1004** [comment]
nice.
